# Arm CAN interfaces
LEFT_FOLLOWER_CAN_INTERFACE = "can_follow_l"
RIGHT_FOLLOWER_CAN_INTERFACE = "can_follow_r"
LEFT_LEADER_CAN_INTERFACE = "can_leader_l"
RIGHT_LEADER_CAN_INTERFACE = "can_leader_r"

# Arm server ports
LEFT_FOLLOWER_PORT = 11333
RIGHT_FOLLOWER_PORT = 11334
LEFT_LEADER_PORT = 11335
RIGHT_LEADER_PORT = 11336
PICO_PORT = 8963
